# -*- coding: utf-8 -*-
"""Tarea 2 ML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pruY--SIKttVbwsJav1Cb84YABXUcVt6

Bienvenido a la semana 2, del curso de Python desde cero de Zero2Hero, en esta semana aprenderemos a usar ciclos, funciones asi como las principales estructuras de programación que existen en Python, además aprenderas los fundamentos de programación orientada a objetos, para que tus programas lleguen a otro nivel.


En la primera sección de este notebook, daremos un repaso de la teoria que hemos visto durante las clases, y al final tendras algunos problemas para que puedas repasar lo aprendido, te recomiendo que los hagas pues de esta manera realmente aprenderas a programar y podras seguir el temario del curso sin la menor dificultad.

Recuerda que siempre puedes mandarme mensaje por whats, si es que te surge alguna duda al resolver este tipo de problemas.

###Ciclos

####Estructura for

Los bucles for son una de las principales estructuras de control en Python que te permiten repetir un bloque de código varias veces.

La sintaxis básica de un bucle for es la siguiente
"""

frutas = ['manzana', 'banana', 'cereza']


for fruta in frutas:  #ciclo for
    print(fruta)

"""Observa que aqui el ciclo for se ejecuta 3 veces una por cada fruta que hay en la lista de frutas, obsevarmos que la variable fruta en la primer ejecución es igual a manzana, en la segunda ejecución es igual a banana y en la tercera ejecución es igual a cereza.

El bucle se detiene después de la tercera iteración porque ya no quedan más elementos en la lista.

Otro ejemplo útil es el uso de la función range(), que genera una secuencia de números:
"""

for i in range(5):
    print(i)

"""Este código imprimirá los números del 0 al 4. La función range(5) genera una secuencia de números del 0 al 4, y en cada iteración del bucle, i toma el siguiente número de la secuencia.

También es posible iterar sobre cadenas de texto, donde la variable de bucle tomará el valor de cada carácter de la cadena:
"""

palabra = 'hola'
for letra in palabra:
    print(letra)

"""Una característica importante de los bucles for es que puedes usar la declaración break para detener el bucle antes de que haya pasado por todos los elementos:"""

numeros = [1, 2, 3, 4, 5]
for numero in numeros:
    if numero == 4:
        break
    print(numero)

"""#### Estructura while

En Python, la declaración while se utiliza para ejecutar un bloque de código varias veces, siempre que una determinada condición sea verdadera.

La sintaxis de un bucle while es la siguiente:

while condición:
    # bloque de código

Donde condición es una expresión booleana que se evalúa en cada iteración del bucle. Si la condición es verdadera, el bloque de código dentro del bucle se ejecuta. Si la condición se vuelve falsa, el bucle termina y la ejecución continúa con la siguiente línea de código después del bucle.
"""

contador = 0
while contador < 5:
    print(contador)
    contador += 1  # Incrementa el contador en 1

"""En este código, contador < 5 es la condición del bucle **while**. En la primera iteración, contador es 0, por lo que la condición es verdadera y el bloque de código dentro del bucle se ejecuta, imprimiendo 0. Luego, contador se incrementa en 1, por lo que en la segunda iteración contador es 1, y así sucesivamente. Cuando contador llega a 5, contador < 5 se vuelve falso, por lo que el bucle termina.

Los bucles while pueden ser controlados con las declaraciones **break** y **continue**, de manera similar a los bucles for. La declaración break se utiliza para salir del bucle prematuramente:
"""

contador = 0
while contador < 5:
    if contador == 3:
        break
    print(contador)
    contador += 1

"""Este código solo imprimirá los números del 0 al 2, porque cuando contador llega a 3, se ejecuta la declaración break y el bucle termina.

La declaración continue se utiliza para saltarse el resto del bloque de código en la iteración actual y continuar con la siguiente iteración:
"""

contador = 0
while contador < 5:
    contador += 1
    if contador == 3:
        continue
    print(contador)

"""Este código imprimirá los números 1, 2, 4, 5. Cuando contador es 3, se ejecuta la declaración continue, por lo que el comando print(contador) se omite y el bucle continúa con la siguiente iteración.

###Listas:

Las listas son una de las estructuras de datos más básicas en Python. Son un tipo de contenedor que se utiliza para almacenar varios objetos de datos, que pueden ser de diferentes tipos (enteros, cadenas, booleanos, objetos, etc.). Se definen con corchetes **[ ]** y los elementos de la lista se separan por comas.
"""

mi_lista = [1, 2, 3, 'a', 'b', 'c', True, False]

print(mi_lista)

"""Algunas operaciones que se pueden realizar con las listas son:

**Añadir elementos: mi_lista.append('Nuevo elemento')**

**Eliminar elementos: mi_lista.remove('a')**

**Acceder a un elemento por su índice: mi_lista[0] (esto devolverá el primer elemento, porque los índices en Python empiezan en 0)**

**Iterar sobre los elementos de la lista:**
"""

#Añadir elementos al final de la lista

mi_lista.append('Nuevo elemento')

print(mi_lista)

#insertar elementos en una posición especifica

mi_lista.insert(1, 'Nuevo elemento en la posición 2')  # Los índices empiezan desde 0.

print(mi_lista)

#eliminar elementos por su valor

mi_lista.remove('a')  # Elimina el primer 'a' que encuentre.

print(mi_lista)  #nota que el elemento a, ya no aparece en la lista

#eliminar elementos por su posición


del mi_lista[0]  # Elimina el primer elemento de la lista.

print(mi_lista)

"""En Python, los índices negativos se utilizan para contar elementos a partir del final de la lista."""

#acceder al primer y ultimo elemento de la lista

primer_elemento = mi_lista[0]  # Obtiene el primer elemento.
ultimo_elemento = mi_lista[-1]  # Obtiene el último elemento.


print(primer_elemento)
print(ultimo_elemento)

# Cambiar el valor de un elemento por su índice

mi_lista[0] = 'Nuevo primer elemento'

print(mi_lista)

#Obtener el índice de un elemento

indice = mi_lista.index('b')  # Devuelve el índice de la primera ocurrencia de 'b'.

print(indice)

#ordenar los elementos de una lista

numeros = [5, 2, 3, 1, 4]
numeros.sort()

print(numeros)

##revertir el orden de los elementos de una lista

numeros.reverse()

print(numeros)

#iterar sobre los elementos de una lista

for elemento in mi_lista:
    print(elemento)

##Comprobar si un elemento esta en la lista

if 'b' in mi_lista:
    print("'b' está en la lista")

##Obtener el número de elementos de una lista

num_elementos = len(mi_lista)


print(mi_lista)
print("El número de elementos es", num_elementos)

#Tomar una sublista de tu lista completa

print(mi_lista[1:4]) #imprime los elementos en la posición 1,2,3 nota el ultimo no lo imprime

print(mi_lista[:4]) #imprime todos los elementos hasta la posición 4, sin imprimir la 4

print(mi_lista[3:]) #imprime todos los elementos desde la posición 3 (incluyendo la posición 3)

"""###Diccionarios

 Los diccionarios son una estructura de datos muy útil en Python. Un diccionario almacena pares de clave-valor, donde cada clave es única. Las claves y los valores pueden ser de cualquier tipo.

Un diccionario en Python se crea utilizando llaves {} con los pares clave-valor separados por dos puntos :. Aquí tienes un ejemplo de cómo crear un diccionario
"""

mi_diccionario = {"nombre": "Mario", "edad": 25, "ocupacion": "plomero"}
print(mi_diccionario)

"""En este caso, "nombre", "edad" y "ocupacion" son las claves, y "Mario", 25 y "plomero" son los valores correspondientes.

Para acceder a un valor en un diccionario, se utiliza la clave correspondiente de la siguiente manera:
"""

print(mi_diccionario["nombre"])  # Imprime "Mario"

"""Si intentas acceder a un diccionario con una clave que no existe, Python te dará un error. Para evitar esto, puedes utilizar el método get(), que devolverá None si la clave no se encuentra en el diccionario:"""

print(mi_diccionario.get("altura"))  # Imprime "None"

"""Puedes modificar el valor de una clave existente o añadir un nuevo par clave-valor a un diccionario de la siguiente manera:"""

mi_diccionario["altura"] = 175  # Añade un nuevo par clave-valor
mi_diccionario["edad"] = 26  # Modifica el valor de la clave "edad"
print(mi_diccionario)  # Imprime {'nombre': 'Mario', 'edad': 26, 'ocupacion': 'plomero', 'altura': 175}

"""Para eliminar un par clave-valor de un diccionario, puedes usar la declaración **del**:"""

del mi_diccionario["altura"]
print(mi_diccionario)  # Imprime {'nombre': 'Mario', 'edad': 26, 'ocupacion': 'plomero'}

"""También puedes obtener todas las claves, todos los valores o todos los pares clave-valor de un diccionario usando los métodos keys(), values() y items(), respectivamente"""

print(mi_diccionario.keys())  # Imprime ['nombre', 'edad', 'ocupacion']
print(mi_diccionario.values())  # Imprime ['Mario', 26, 'plomero']
print(mi_diccionario.items())  # Imprime [('nombre', 'Mario'), ('edad', 26), ('ocupacion', 'plomero')]

"""Ahora, vamos con un ejemplo divertido. Supongamos que estás creando un juego de rol y quieres almacenar información sobre los personajes. Podrías usar un diccionario para hacerlo. Por ejemplo"""

personajes = {
    "Mario": {"ocupacion": "plomero", "poder": "saltar alto", "vida": 100},
    "Luigi": {"ocupacion": "plomero", "poder": "saltar aún más alto", "vida": 100},
    "Bowser": {"ocupacion": "rey", "poder": "lanzar fuego", "vida": 500},
}

# Imprimir información sobre Mario
print(personajes["Mario"])

# Reducir la vida de Bowser en 50
personajes["Bowser"]["vida"] -= 50
print(personajes["Bowser"])

"""###Funciones

Las funciones son un pilar fundamental de la programación en Python y en la mayoría de los lenguajes de programación.

Una función es un bloque de código reutilizable que realiza una acción específica. Puedes pensar en una función como una máquina: le das ciertas entradas, hace algo con ellas y luego produce una salida.

La sintaxis para definir una función en Python es la siguiente:
"""

def nombre_de_la_funcion(argumentos):
    # Código de la función
    return valor_de_retorno

"""Aquí, def es una palabra clave que indica que estás definiendo una función. **nombre_de_la_funcion** es el nombre que eliges para la función, y **argumentos** es una lista de variables que la función tomará como entrada. El código de la función es el bloque de código que se ejecutará cuando se llame a la función. **return** es otra palabra clave que indica el valor que la función dará como resultado.

Veamos un ejemplo sencillo:
"""

def sumar_dos_numeros(a, b):
    suma = a + b
    return suma

resultado = sumar_dos_numeros(5, 3)
print(resultado)  # Imprime 8

"""En este caso, sumar_dos_numeros es una función que toma dos argumentos, a y b, y devuelve su suma. Cuando llamamos a sumar_dos_numeros(5, 3), la función se ejecuta con a igual a 5 y b igual a 3, y devuelve la suma de estos dos números, que es 8.

Las funciones pueden tener cualquier número de argumentos, incluso ninguno. Aquí tienes un ejemplo de una función sin argumentos:
"""

def imprimir_mensaje():
    print("¡Hola, mundo!")

imprimir_mensaje()  # Imprime "¡Hola, mundo!"

"""Puedes usar la declaración return para devolver cualquier tipo de valor desde una función, incluyendo listas, diccionarios, o incluso otras funciones. Si no incluyes una declaración return en tu función, por defecto devolverá None.

Las funciones son extremadamente útiles para organizar tu código y hacerlo más legible y reutilizable. En lugar de tener que escribir el mismo código una y otra vez, puedes encapsular ese código en una función y luego llamar a la función cada vez que necesites realizar esa acción. Las funciones también son una excelente manera de dividir un programa complejo en partes más pequeñas y manejables.

Ahora veamos un ejemplo más divertido e interesante. Supongamos que estás escribiendo un programa para simular un juego de lanzamiento de dados. Podrías escribir una función para simular el lanzamiento de un dado:
"""

import random

def lanzar_dado():
    return random.randint(1, 6)

for i in range(5):
    print(lanzar_dado())

"""Aquí, lanzar_dado es una función que no toma ningún argumento y devuelve un número aleatorio entre 1 y 6, simulando el lanzamiento de un dado. Luego lanzamos el dado 5 veces e imprimimos el resultado de cada lanzamiento.

#Tarea

Dada una lista de números, escribe un programa que encuentre el número más grande en la lista. **Nota: No se vale usar la función max **
"""

mi_lista = [2,1,4,10,-3,23,11,12,38,11]

#aqui va tu codigo

"""Dado un diccionario que almacena las edades de las personas, escribe un programa que encuentre la persona de mayor edad y su edad."""

edades = {
    'Mario': 30,
    'Luigi': 35,
    'Peach': 32,
    'Bowser': 58,
    'Toad': 20
}

# Aquí va tu código

"""3. Ejercicio con ciclos:

Escribe un programa que imprima los primeros 30 números de la serie de Fibonacci (0, 1, 1, 2, 3, 5, 8, 13, 21, 34).

La serie de fibonacci usa la siguiente regla el primer número es $0$ luego sigue $1$ y los siguientes son la suma de los dos anteriores asi el tercer elemento es $0+1 = 1$, el cuarto elemento es $1+1=2$, el quinto elemento es $1+2=3$ y asi sucesivamente.
"""

#aqui va tu codigo

"""2. Calculadora de Propinas:

Escribe una función que tome el total de una cuenta de restaurante y el porcentaje de propina que quieres dejar. La función debería devolver la cantidad de dinero que debes dejar como propina.
"""

#aqui va el codigo

"""Piedra, papel o tijeras:

Escribe una función que simule el juego de "Piedra, papel o tijeras". La función debe tomar la elección del jugador como entrada (piedra, papel o tijeras) y luego generar al azar la elección de la computadora. La función debe determinar quién gana el juego y devolver el resultado.
"""

#Aqui va el codigo

"""Escribe una función que valide si una cadena de texto es un correo electrónico válido. Un correo electrónico válido debe tener al menos un carácter antes del símbolo @, seguido por al menos un carácter y un punto, y luego debe terminar con "com", "net" o "org"
"""

#aqui va el codigo